services:
  xqsim-backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    shm_size: "2gb"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1


